base_url: https://blog.otso.fr/
site_name: Blob Trotter
description: Les pérégrinations d'un développeur dans le monde de Javascript et de Go
theme: otso
build_path: ./docs

robots: index, follow

opengraph:
  type: article

twitter:
  card: summary
  creator: adriantombu
  site: adriantombu
